IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_PRICING_RATE_PACKAGE_MODEL_VERSION'
      AND object_id = OBJECT_ID('pricing.PRICING_RATE_PACKAGE')
)
CREATE UNIQUE INDEX UX_PRICING_RATE_PACKAGE_MODEL_VERSION
ON pricing.PRICING_RATE_PACKAGE(model_id, package_version)
WHERE model_id IS NOT NULL;
GO
